### ISSUE TITLE
'[…]/.tmux/plugins/tmux-menus/scripts/break_pane.sh' returned 127

### ISSUE THREAD

**Issue by phdoerfler** [jaclu/tmux-menus#37]
I tried breaking out a pane using `Handling Pane` -> `Move Pane` -> `Break pane to a new window` and instead of doing that, tmux presented me with the following message:

```
'/home/philipp/.tmux/plugins/tmux-menus/scripts/break_pane.sh' returned 127
```

I just installed tmux-menus through TPM moments ago. My tmux is 3.2a on Ubuntu.

**Comment by phdoerfler** [comment]
It would appear, that `TMUX_BIN` in the `break_pane.sh script is not set. Is that something the user is expected to set in their shell rc file?

**Comment by jaclu** [comment]
checking...

**Comment by jaclu** [comment]
I tried it with 3.2a and for me it works :)

But more seriously, since you just installed it, it would seem safe to assume you are using the current version of things.
This is how the relevant lines in break_pane.sh looks like

```
if [ "$($TMUX_BIN list-panes | wc -l)" -lt 2 ]; then
    $TMUX_BIN display-message "Only one pane!"
else
    $TMUX_BIN command-prompt -I "#W" -p "New window name: " \
        "break-pane -n '%%'"
fi
```

If you have more than one pane on the window, the else case would handle this
and even if displayed as two lines, from a script perspective it is just one.
I often extend lines with \ in order to make them not spreading out to far to the right.

When this snippet is processed by the shell the above is read as

```
$TMUX_BIN command-prompt -I "#W" -p "New window name: " "break-pane -n '%%'"
```

So in general I think this command works as intended.

Back to your problem with the error. At this point I have to little info to be able to speculate, could you perhaps try "Reload configuration file" on the main menu?
It also uses $TMUX_BIN in a similar fashion, so if it also fails it would point towards this variable not being propperly set. If it succeedes something else is causing this.

**Comment by jaclu** [comment]
If you are familiar with editing scripts you could also do this procedure to see what this variable is set to:

in `/home/philipp/.tmux/plugins/tmux-menus/scripts/break_pane.sh`
insert this line before the if condition starts on line 13

```sh
echo "TMUX_BIN is [$TMUX_BIN]"
```

When you next try Break pane to new window, you will get some debug output printed, a line starting with "TMUX_BIN is ["
the interesting thing to look for is the content between [] this is where this plugin thinks your tmux bin is located. it should be at least [tmux] If it is empty it indicates that something went wrong.

**Comment by phdoerfler** [comment]
That’s exactly how I arrived at this conclusion:
> It would appear, that `TMUX_BIN` in the `break_pane.sh script is not set. Is that something the user is expected to set in their shell rc file?

If I echo $TMUX_BIN I get an empty string.

**Comment by jaclu** [comment]
My bad, you wrote that clearly, somehow I totally misunderstood you and thought you didnt get line splitting. Sorry for an uncalled for lecture :(

So in hindsight, thanx for a well formulated bug report!

You are totally correct, I had forgotten to set it in at least that script

I just realized that since I have TMUX_BIN set as an env variable in my .tmux.conf this type of mistake would never trigger during my testings.

Will do testing without the variable preset, to ensure everything works as expected and will ensure it is assigned everywhere it is needed.

I expect to commit a fully tested update by tomorrow.

If you are impatient, just add this snippet in any script/menu where this issue is present.

```sh
CURRENT_DIR=$(cd -- "$(dirname -- "$0")" && pwd)
SCRIPT_DIR="$(dirname "$CURRENT_DIR")/scripts"

# shellcheck disable=SC1091
. "$SCRIPT_DIR/utils.sh"
```

**Comment by jaclu** [comment]
I have added checks everywhere that TMUX_BIN has been defined, so hopefully this issue should be resolved
